# Generated by Django 5.2.5 on 2025-09-03 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloglistmodel',
            name='description',
        ),
    ]
